package Tools;

public enum State {
    WAITING_COMMAND,
    BUYING,
    MAKING_COFFEE,
    REFILLING,
    REFILLING_WATER,
    REFILLING_MILK,
    REFILLING_BEANS,
    REFILLING_CUPS,
    GIVING_MONEY,
    PRINTING_INFORMATION,
    EXITING,
    HANDLING_ERROR
}